Repository SU-SWS/react_paragraphs, pull requests merged in 2020-09, with the labels that each got.

#60 Decode double encoded json array
  react_paragraphs.install
Labels: size/xs

#61 Added form settings to set the maximum column widths
  config/schema/react_paragraphs.schema.yml
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  src/Plugin/Field/FieldWidget/ReactParagraphsWidgetBase.php
  tests/src/Kernel/Plugin/Field/FieldWidget/ReactParagraphsWidgetTest.php
Labels: backend, size/xs

#66 Update react_paragraphs.install
  react_paragraphs.install
Labels: size/xs

#67 8.2.1
  CHANGELOG.md
  react_paragraphs.info.yml
  react_paragraphs.install
Labels: patch, size/xs

#68 Fix the upgrade for mismatched paragraph revisions
  react_paragraphs.install
Labels: patch, size/xs

#69 D8CORE-2150: Adjust link widget to mirror the php link widget
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/LinkWidget.js
Labels: frontend, size/s
