Repository SU-SWS/react_paragraphs, pull requests merged in 2020-04, with the labels that each got.

#34 D8CORE-1548 Dont trigger form updated on component load
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/WidgetManager.js
Labels: frontend, size/xs

#36 D8CORE-1644 Added documentation for the release workflow
  .github/workflows/release.yml
  README.md
Labels: ci, size/xs

#35 D8CORE-1829 Visual tweaks and API call adjustments
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Atoms/Loader.js
  js/src/Components/Paragraph.js
  js/src/Components/ParagraphForm.js
  js/src/WidgetManager.js
  package-lock.json
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  tests/src/Kernel/Plugin/Field/FieldWidget/ReactParagraphsWidgetTest.php
  yarn.lock
Labels: backend, ci, frontend, size/xl

#37 Filter Row order to get rid of null values
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/WidgetManager.js
Labels: frontend, size/xs

#39 Provide error handeling for media library widget
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/MediaLibrary.js
Labels: frontend, size/xs

#38 Release 8.1.7
  .circleci/config.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Atoms/Loader.js
  js/src/Components/Paragraph.js
  js/src/Components/ParagraphForm.js
  js/src/Components/Widgets/MediaLibrary.js
  js/src/WidgetManager.js
  package-lock.json
  react_paragraphs.info.yml
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  tests/src/Kernel/Plugin/Field/FieldWidget/ReactParagraphsWidgetTest.php
  yarn.lock
Labels: ci, patch, size/xs

#40 D8CORE-1823 Fix link widget when the user inputs <front>
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Widgets/LinkWidget.js
  package-lock.json
  yarn.lock
Labels: frontend, size/s
