Repository SU-SWS/react_paragraphs, pull requests merged in 2020-05, with the labels that each got.

#41 D8CORE-1943 Fix the link widget and how it handles the suggestions and absolute urls
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/LinkWidget.js
Labels: frontend, size/xs

#44 D8CORE-000: Allow post getFieldInfo altering.
  .codeclimate.yml
  react_paragraphs.api.php
  src/Plugin/rest/resource/ReactParagraphsResource.php
  tests/src/Unit/Plugin/rest/resource/ReactParagraphsResourceTest.php
Labels: backend, size/xs

#46 viewfield2 b
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/ViewFieldWidget.js
  react_paragraphs.api.php
  src/Plugin/rest/resource/ReactParagraphsResource.php
Labels: backend, frontend, size/xs

#47 "8.x-1.x > 8.1.8
  .codeclimate.yml
  CHANGELOG.md
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Widgets/LinkWidget.js
  js/src/Components/Widgets/ViewFieldWidget.js
  package-lock.json
  react_paragraphs.api.php
  react_paragraphs.info.yml
  src/Plugin/rest/resource/ReactParagraphsResource.php
  tests/src/Unit/Plugin/rest/resource/ReactParagraphsResourceTest.php
  yarn.lock
Labels: backend, frontend, patch, size/s
