Repository SU-SWS/react_paragraphs, pull requests merged in 2020-10, with the labels that each got.

#70 D8CORE-2685 Discover behaviors defined in modules and themes yml
  composer.json
  config/schema/paragraphs_row_type.schema.yml
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/EntityForm.js
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.info.yml
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.module
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.react_behaviors.yml
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.services.yml
  modules/react_paragraphs_behaviors/src/Config/ConfigOverrides.php
  modules/react_paragraphs_behaviors/src/Plugin/Derivative/ReactBehaviorsDeriver.php
  modules/react_paragraphs_behaviors/src/Plugin/paragraphs/Behavior/ReactBehaviors.php
  modules/react_paragraphs_behaviors/src/ReactBehaviorsPluginManager.php
  modules/react_paragraphs_behaviors/src/ReactBehaviorsPluginManagerInterface.php
  modules/react_paragraphs_behaviors/tests/src/Kernel/Plugin/paragraphs/Behavior/ReactBehaviorsTest.php
  modules/react_paragraphs_behaviors/tests/src/Kernel/ReactBehaviorsPluginManagerTest.php
  modules/react_paragraphs_behaviors/tests/test_react_paragraphs_behaviors/test_react_paragraphs_behaviors.info.yml
  modules/react_paragraphs_behaviors/tests/test_react_paragraphs_behaviors/test_react_paragraphs_behaviors.react_behaviors.yml
  src/Plugin/rest/resource/ReactParagraphsResource.php
Labels: backend, frontend, patch, size/m

#71 Fixed logger message
  src/Plugin/Field/FieldWidget/ReactParagraphsWidgetBase.php
Labels: backend, size/xs

#72 Fixed paragraph entity form modal label
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/RowItem.js
Labels: frontend, size/xs

#73 8.2.2
  CHANGELOG.md
  composer.json
  config/schema/paragraphs_row_type.schema.yml
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/EntityForm.js
  js/src/Components/RowItem.js
  js/src/Components/Widgets/LinkWidget.js
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.info.yml
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.module
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.react_behaviors.yml
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.services.yml
  modules/react_paragraphs_behaviors/src/Config/ConfigOverrides.php
  modules/react_paragraphs_behaviors/src/Plugin/Derivative/ReactBehaviorsDeriver.php
  modules/react_paragraphs_behaviors/src/Plugin/paragraphs/Behavior/ReactBehaviors.php
  modules/react_paragraphs_behaviors/src/ReactBehaviorsPluginManager.php
  modules/react_paragraphs_behaviors/src/ReactBehaviorsPluginManagerInterface.php
  modules/react_paragraphs_behaviors/tests/src/Kernel/Plugin/paragraphs/Behavior/ReactBehaviorsTest.php
  modules/react_paragraphs_behaviors/tests/src/Kernel/ReactBehaviorsPluginManagerTest.php
  modules/react_paragraphs_behaviors/tests/test_react_paragraphs_behaviors/test_react_paragraphs_behaviors.info.yml
  modules/react_paragraphs_behaviors/tests/test_react_paragraphs_behaviors/test_react_paragraphs_behaviors.react_behaviors.yml
  react_paragraphs.info.yml
  react_paragraphs.install
  src/Plugin/Field/FieldWidget/ReactParagraphsWidgetBase.php
  src/Plugin/rest/resource/ReactParagraphsResource.php
Labels: backend, frontend, patch, size/l

#74 D8CORE-2709 Entity Reference Autocomplete & Select support
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/EntityForm.js
  js/src/Components/Widgets/AutocompleteReferenceWidget.js
  src/Plugin/Field/ReactParagraphsFields/EntityReference.php
  tests/src/Kernel/Plugin/Field/ReactParagraphsFields/EntityReferenceTest.php
Labels: backend, frontend, patch, size/s

#75 D8CORE-2852: Add ckeditor event listener for changes
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/CkeditorWidget.js
Labels: frontend, size/xs

#76 Fix default values in autocomplete and allow special characters in text fields
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/AutocompleteReferenceWidget.js
  js/src/Contexts/WidgetManager.js
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  src/Plugin/Field/ReactParagraphsFields/EntityReference.php
  tests/src/Unit/Plugin/Field/ReactParagraphsFields/ReactParagraphsFieldsTestBase.php
Labels: backend, frontend, size/xs
