Repository SU-SWS/react_paragraphs, pull requests merged in 2020-11, with the labels that each got.

#77 D8CORE-2686 Paragraph and row behaviors UI
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Atoms/ErrorBoundary.js
  js/src/Components/Atoms/FormDialog.js
  js/src/Components/Atoms/Loader.js
  js/src/Components/Atoms/RowActions.js
  js/src/Components/Behaviors.js
  js/src/Components/EntityForm.js
  js/src/Components/ParagraphForm.js
  js/src/Components/RowForm.js
  js/src/Components/Widgets/CheckboxesWidget.js
  js/src/Components/Widgets/SelectWidget.js
  js/src/Components/Widgets/ViewFieldWidget.js
  js/src/Contexts/WidgetManager.js
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.react_behaviors.yml
  src/Entity/ParagraphRow.php
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  tests/src/Kernel/Plugin/Field/FieldWidget/ReactParagraphsWidgetTest.php
  yarn.lock
Labels: backend, frontend, size/xl

#78 D8CORE-2857 keep upper case characters in link fields
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Widgets/AutocompleteReferenceWidget.js
  js/src/Components/Widgets/CheckboxesWidget.js
  js/src/Components/Widgets/LinkWidget.js
  js/src/Components/Widgets/MediaLibrary.js
  js/src/Components/Widgets/SelectWidget.js
  js/src/Components/Widgets/ViewFieldWidget.js
Labels: frontend, size/xs

#80 "8.x-2.x > 8.2.3
  CHANGELOG.md
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Atoms/ErrorBoundary.js
  js/src/Components/Atoms/FormDialog.js
  js/src/Components/Atoms/Loader.js
  js/src/Components/Atoms/RowActions.js
  js/src/Components/Behaviors.js
  js/src/Components/EntityForm.js
  js/src/Components/ParagraphForm.js
  js/src/Components/RowForm.js
  js/src/Components/Widgets/AutocompleteReferenceWidget.js
  js/src/Components/Widgets/CheckboxesWidget.js
  js/src/Components/Widgets/CkeditorWidget.js
  js/src/Components/Widgets/LinkWidget.js
  js/src/Components/Widgets/MediaLibrary.js
  js/src/Components/Widgets/SelectWidget.js
  js/src/Components/Widgets/ViewFieldWidget.js
  js/src/Contexts/WidgetManager.js
  modules/react_paragraphs_behaviors/react_paragraphs_behaviors.react_behaviors.yml
  react_paragraphs.info.yml
  src/Entity/ParagraphRow.php
  src/Plugin/Field/FieldWidget/ReactParagraphs.php
  src/Plugin/Field/ReactParagraphsFields/EntityReference.php
  tests/src/Kernel/Plugin/Field/FieldWidget/ReactParagraphsWidgetTest.php
  tests/src/Kernel/Plugin/Field/ReactParagraphsFields/EntityReferenceTest.php
  tests/src/Unit/Plugin/Field/ReactParagraphsFields/ReactParagraphsFieldsTestBase.php
  yarn.lock
Labels: backend, frontend, patch, size/xl

#81 Added config export for D9 Requirements
  src/Entity/ParagraphsRowType.php
Labels: backend, size/xs

#82 Update tests for D9 phpunit
  tests/src/Kernel/Form/ParagraphsRowTypeDeleteFormTest.php
Labels: backend, size/xs

#83 D8CORE-1420 Fix the ckeditor toolbar when scrolling down the item.
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/CkeditorWidget.js
Labels: frontend, size/xs
