Repository SU-SWS/react_paragraphs, pull requests merged in 2020-06, with the labels that each got.

#48 D8CORE-2106
  js/build/app.js
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/build/vendor.js
  js/src/Components/Widgets/LinkWidget.js
  package-lock.json
Labels: frontend, size/s

#50 Allow unlimited media library cardinality
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Widgets/MediaLibrary.js
Labels: frontend, size/xs

#52 "8.x-1.x > 8.1.9
  CHANGELOG.md
  js/build/app.js
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/build/vendor.js
  js/src/Components/Widgets/LinkWidget.js
  js/src/Components/Widgets/MediaLibrary.js
  package-lock.json
  react_paragraphs.info.yml
  yarn.lock
Labels: frontend, patch, size/l
