Repository SU-SWS/react_paragraphs, pull requests merged in 2021-02, with the labels that each got.

#88 8.2.5
  .circleci/config.yml
  CHANGELOG.md
  config/optional/rest.resource.entity.paragraph_row.yml
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/src/Components/Atoms/ErrorBoundary.js
  js/src/Components/Atoms/Loader.js
  js/src/Components/EntityForm.js
  js/src/Components/Widgets/Media/MediaLibrary.js
  js/src/Components/Widgets/Media/MediaList.js
  react_paragraphs.info.yml
Labels: ci, frontend, patch, size/s

#89 D8CORE-3392 Sort the view displays based on their order in the view
  src/Plugin/Field/ReactParagraphsFields/View.php
  src/ReactParagraphsFieldsInterface.php
  tests/src/Unit/Plugin/Field/ReactParagraphsFields/ViewTest.php
Labels: backend, size/xs

#90 D8CORE-3380 Allow media library widget to be sortable
  js/build/react_paragraphs.app.min.js
  js/build/react_paragraphs.app.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js
  js/build/react_paragraphs.react_paragraphs.field_formatter.min.js.map
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js
  js/build/react_paragraphs.react_paragraphs.field_widget.min.js.map
  js/build/react_paragraphs.vendor.min.js
  js/build/react_paragraphs.vendor.min.js.map
  js/src/Components/Atoms/FormDialog.js
  js/src/Components/Widgets/Media/MediaLibrary.js
  js/src/Components/Widgets/Media/MediaList.js
  package.json
  yarn.lock
Labels: frontend, size/s
